#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "PhotoPicker" do
    pod 'DZNPhotoPickerController'#, :path => '../../'

end

target "Tests" do
    pod 'Kiwi', '~> 2.3'
end
