#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target "PhotoPicker" do
    pod 'DZNPhotoPickerController', :path => '../../'

end

target "Tests" do
  pod 'DZNPhotoPickerController', :path => '../../'
  pod 'Kiwi', '~> 3.0'
end
